r"""
    Module which provides conversion of Unicode strings to LaTeX.
    Only a subset of the Unicode space is covered, including ASCII,
    all of Latin-1, and a few characters from Latin-2.

    Public function convert() takes a Unicode string and returns
    an ASCII LaTeX string.

    The LaTeX document in which these strings are inserted must
    have the following two lines in the preamble:

        \usepackage{textcomp}
        \newcommand{\Special}[1]{{\fontencoding{T1}\selectfont\symbol{#1}}}

    You can grab them with the public function getPreamble().

    It's also possible to use the module's latexForUnicodeChar() function
    directly to convert a single Unicode character (which is the only
    argument passed) to a LaTeX string.

    Note that this version does not provide the trick of alternating
    opening and closing quotes for u'"'.
"""

#----------------------------------------------------------------------
#
# $Id: UnicodeToLatex.py,v 1.3 2002-11-08 21:47:59 bkline Exp $
#
# $Log: not supported by cvs2svn $
# Revision 1.2  2001/10/20 18:46:59  bkline
# Filled in a few holes; used dot-less i for accented glyphs.
#
# Revision 1.1  2001/10/20 04:19:03  bkline
# Initial revision
#
#----------------------------------------------------------------------

import re
codeMap = {
    0x0022: r"""\tQ{}""",
    0x0023: r"""\#""",
    0x0024: r"""\$""",
    0x0025: r"""$\%$""",
    0x0026: r"""\&""",
    0x003C: r"""$<$""",
    0x003E: r"""$>$""",
    0x005B: r"""$\lbrack$""",
    0x005C: r"""$\backslash$""",
    0x005D: r"""$\rbrack$""",
    0x005E: r"""\^{}""",
    0x005F: r"""\_{}""",
    0x0060: r"""\`{}""",
    0x007B: r"""\{""",
    0x007C: r"""\Special{"7C}""",
    0x007D: r"""\}""",
    0x007E: r"""\textasciitilde{}""",
    0x00A0: r"""~""",
    0x00A1: r"""\Special{"BD}""",
    0x00A2: r"""\textcent{}""",
    0x00A3: r"""\textsterling{}""",
    0x00A4: r"""\textcurrency{}""",
    0x00A5: r"""\textyen{}""",
    0x00A6: r"""\textbrokenbar{}""",
    0x00A7: r"""\textsection{}""",
    0x00A8: r"""\textasciidieresis{}""",
    0x00A9: r"""\textcopyright{}""",
    0x00AA: r"""\textordfeminine{}""",
    0x00AB: r"""\Special{"13}""",
    0x00AC: r"""\textlnot{}""",
    0x00AD: r"""\-""",
    0x00AE: r"""\textregistered{}""",
    0x00AF: r"""\textasciimacron{}""",
    0x00B0: r"""\textdegree{}""",
    0x00B1: r"""\textpm{}""",
    0x00B2: r"""\texttwosuperior{}""",
    0x00B3: r"""\textthreesuperior{}""",
    0x00B4: r"""\textasciiacute{}""",
    0x00B5: r"""\textmu{}""",
    0x00B6: r"""\textpilcrow{}""",
    0x00B7: r"""$\cdot$""",
    0x00B8: r"""\Special{"0B}""",
    0x00B9: r"""\textonesuperior{}""",
    0x00BA: r"""\textordmasculine{}""",
    0x00BB: r"""\Special{"14}""",
    0x00BC: r"""\textonequarter{}""",
    0x00BD: r"""\textonehalf{}""",
    0x00BE: r"""\textthreequarters{}""",
    0x00BF: r"""\Special{"BE}""",
    0x00D7: r"""\texttimes{}""",
    0x00DF: r"""\Special{"FF}""",
    0x00F7: r"""\textdiv{}""",
    0x00FF: r"""\Special{"B8}""",
    0x0100: r"""\={A}""",
    0x0101: r"""\={a}""",
    0x0102: r"""\u{A}""",
    0x0103: r"""\u{a}""",
    0x0104: r"""\Special{"81}""",
    0x0105: r"""\Special{"A1}""",
    0x0106: r"""\'{C}""",
    0x0107: r"""\'{c}""",
    0x0108: r"""\^{C}""",
    0x0109: r"""\^{c}""",
    0x010A: r"""\.{C}""",
    0x010B: r"""\.{c}""",
    0x010C: r"""\v{C}""",
    0x010D: r"""\v{c}""",
    0x010E: r"""\v{D}""",
    0x010F: r"""\v{d}""",
    0x0110: r"""\Special{"D0}""",
    0x0111: r"""\Special{"9E}""",
    0x0112: r"""\={E}""",
    0x0113: r"""\={e}""",
    0x0114: r"""\u{E}""",
    0x0115: r"""\u{e}""",
    0x0116: r"""\.{E}""",
    0x0117: r"""\.{e}""",
    0x0118: r"""\Special{"86}""",
    0x0119: r"""\Special{"A6}""",
    0x011A: r"""\v{E}""",
    0x011B: r"""\v{e}""",
    0x011C: r"""\^{G}""",
    0x011D: r"""\^{g}""",
    0x011E: r"""\u{G}""",
    0x011F: r"""\u{g}""",
    0x0120: r"""\.{G}""",
    0x0121: r"""\.{g}""",
    0x0122: r"""\c{G}""",
    0x0123: r"""\c{g}""",
    0x0124: r"""\^{H}""",
    0x0125: r"""\^{h}""",
    0x0128: r"""\~{I}""",
    0x0129: r"""\~{\i}""",
    0x012A: r"""\={I}""",
    0x012B: r"""\={\i}""",
    0x012C: r"""\u{I}""",
    0x012D: r"""\u{\i}""",
    0x0130: r"""\.{I}""",
    0x0131: r"""\.{\i}""",
    0x0132: r"""\Special{"9C}""",
    0x0133: r"""\Special{"BC}""",
    0x0134: r"""\^{J}""",
    0x0135: r"""\^{\j}""",
    0x0136: r"""\c{K}""",
    0x0137: r"""\c{k}""",
    0x0139: r"""\Special{"88}""",
    0x013A: r"""\Special{"A8}""",
    0x013B: r"""\c{L}""",
    0x013C: r"""\c{l}""",
    0x013D: r"""\v{L}""",
    0x013E: r"""\v{l}""",
    0x013F: r"""\mbox{L$\cdot$}""",
    0x0140: r"""\mbox{I$\cdot$}""",
    0x0141: r"""\Special{"8A}""",
    0x0142: r"""\Special{"AA}""",
    0x0143: r"""\'{N}""",
    0x0144: r"""\'{n}""",
    0x0145: r"""\c{N}""",
    0x0146: r"""\c{n}""",
    0x0147: r"""\v{N}""",
    0x0148: r"""\v{n}""",
    0x0149: r"""'n""",
    0x014A: r"""\Special{"8D}""",
    0x014B: r"""\Special{"AD}""",
    0x014C: r"""\={O}""",
    0x014D: r"""\={o}""",
    0x014E: r"""\u{O}""",
    0x014F: r"""\u{o}""",
    0x0150: r"""\H{O}""",
    0x0151: r"""\H{o}""",
    0x0152: r"""\Special{"D7}""",
    0x0153: r"""\Special{"F7}""",
    0x0154: r"""\'{R}""",
    0x0155: r"""\'{r}""",
    0x0156: r"""\c{R}""",
    0x0157: r"""\c{r}""",
    0x0158: r"""\v{R}""",
    0x0159: r"""\v{r}""",
    0x015A: r"""\'{S}""",
    0x015B: r"""\'{s}""",
    0x015C: r"""\^{S}""",
    0x015D: r"""\^{s}""",
    0x015E: r"""\c{S}""",
    0x015F: r"""\c{s}""",
    0x0160: r"""\v{S}""",
    0x0161: r"""\v{s}""",
    0x0162: r"""\c{T}""",
    0x0163: r"""\c{t}""",
    0x0164: r"""\v{T}""",
    0x0165: r"""\Special{"B4}""",
    0x0168: r"""\~{U}""",
    0x0169: r"""\~{u}""",
    0x016A: r"""\={U}""",
    0x016B: r"""\={u}""",
    0x016C: r"""\u{U}""",
    0x016D: r"""\u{u}""",
    0x016E: r"""\Special{"97}""",
    0x016F: r"""\Special{"B7}""",
    0x0170: r"""\H{U}""",
    0x0171: r"""\H{u}""",
    0x0174: r"""\^{W}""",
    0x0175: r"""\^{w}""",
    0x0176: r"""\^{Y}""",
    0x0177: r"""\^{y}""",
    0x0178: r'''\"{y}''',
    0x0179: r"""\'{Z}""",
    0x017A: r"""\'{z}""",
    0x017B: r"""\.{Z}""",
    0x017C: r"""\.{z}""",
    0x017D: r"""\v{Z}""",
    0x017E: r"""\v{z}""",
    0x01CD: r"""\v{A}""",
    0x01CE: r"""\v{a}""",
    0x01CF: r"""\v{I}""",
    0x01D0: r"""\v{\i}""",
    0x01D1: r"""\v{O}""",
    0x01D2: r"""\v{o}""",
    0x01D3: r"""\v{U}""",
    0x01D4: r"""\v{u}""",
    0x01E2: r"""\={\AE}""",
    0x01E3: r"""\={\ae}""",
    0x01E6: r"""\v{G}""",
    0x01E7: r"""\v{g}""",
    0x01E8: r"""\v{K}""",
    0x01E9: r"""\v{k}""",
    0x01F4: r"""\'{G}""",
    0x01F5: r"""\'{g}""",
    0x01FC: r"""\'{\AE}""",
    0x01FD: r"""\'{\ae}""",
    0x02D8: r"""\u{}""",
    0x02D9: r"""\.{}""",
    0x0300: r"""\`""",
    0x0301: r"""\'""",
    0x0302: r"""\^""",
    0x0303: r"""\~""",
    0x0304: r"""\=""",
    0x0306: r"""\u{}""",
    0x0307: r"""\.""",
    0x0308: r'''\"''',
    0x030B: r"""\H{}""",
    0x030C: r"""\v{}""",
    0x0327: r"""\c{}""",
    0x0391: r"""A""",
    0x0392: r"""B""",
    0x0393: r"""$\Gamma$""",
    0x0394: r"""$\Delta$""",
    0x0395: r"""E""",
    0x0396: r"""Z""",
    0x0397: r"""H""",
    0x0398: r"""$\Theta$""",
    0x0399: r"""I""",
    0x039A: r"""K""",
    0x039B: r"""$\Lambda$""",
    0x039C: r"""M""",
    0x039D: r"""N""",
    0x039E: r"""$\Xi$""",
    0x039F: r"""O""",
    0x03A0: r"""$\Pi$""",
    0x03A1: r"""P""",
    0x03A3: r"""$\Sigma$""",
    0x03A4: r"""T""",
    0x03A5: r"""$\Upsilon$""",
    0x03A6: r"""$\Phi$""",
    0x03A7: r"""X""",
    0x03A8: r"""$\Psi$""",
    0x03A9: r"""$\Omega$""",
    0x03B1: r"""$\alpha$""",
    0x03B2: r"""$\beta$""",
    0x03B3: r"""$\gamma$""",
    0x03B4: r"""$\delta$""",
    0x03B5: r"""$\epsilon$""",
    0x03B6: r"""$\zeta$""",
    0x03B7: r"""$\eta$""",
    0x03B8: r"""$\theta$""",
    0x03B9: r"""$\iota$""",
    0x03BA: r"""$\kappa$""",
    0x03BB: r"""$\lambda$""",
    0x03BC: r"""$\mu$""",
    0x03BD: r"""$\nu$""",
    0x03BE: r"""$\xi$""",
    0x03BF: r"""o""",
    0x03A0: r"""$\pi$""",
    0x03A1: r"""$\rho$""",
    0x03A2: r"""$\varsigma$""",
    0x03A3: r"""$\sigma$""",
    0x03A4: r"""$\tau$""",
    0x03A5: r"""$\upsilon$""",
    0x03A6: r"""$\phi$""",
    0x03A7: r"""$\chi$""",
    0x03A8: r"""$\psi$""",
    0x03A9: r"""$\omega$""",
    0x03D1: r"""$\theta1$""",
    0x03D5: r"""$\varphi$""",
    0x03D6: r"""$\varpi$""",
    0x03F1: r"""$\varrho$""",
    0x2009: r"""\thinspace{}""",
    0x2010: r"""-""",
    0x2011: r"""-""",
    0x2013: r"""--""",
    0x2014: r"""---""",
    0x2016: r"""$\|$""",
    0x2020: r"""\dag{}""",
    0x2021: r"""\ddag{}""",
    0x2022: r"""\textbullet{}""",
    0x2026: r"""\dots{}""",
    0x2032: r"""$\prime$""",
    0x2038: r"""\^{}""",
    0x2070: r"""$^0$""",
    0x2074: r"""$^4$""",
    0x2075: r"""$^5$""",
    0x2076: r"""$^6$""",
    0x2077: r"""$^7$""",
    0x2078: r"""$^8$""",
    0x2079: r"""$^9$""",
    0x207A: r"""$^+$""",
    0x207B: r"""$^-$""",
    0x207C: r"""$^=$""",
    0x207D: r"""$^($""",
    0x207E: r"""$^)$""",
    0x207F: r"""$^n$""",
    0x2080: r"""$_0$""",
    0x2081: r"""$_1$""",
    0x2082: r"""$_2$""",
    0x2083: r"""$_3$""",
    0x2084: r"""$_4$""",
    0x2085: r"""$_5$""",
    0x2086: r"""$_6$""",
    0x2087: r"""$_7$""",
    0x2088: r"""$_8$""",
    0x2089: r"""$_9$""",
    0x208A: r"""$_+$""",
    0x208B: r"""$_-$""",
    0x208C: r"""$_=$""",
    0x208D: r"""$_($""",
    0x208E: r"""$_)$""",
    0x2107: r"""$e$""",
    0x210E: r"""h""",
    0x210F: r"""$\hbar$""",
    0x2111: r"""$\Im$""",
    0x2113: r"""$\ell$""",
    0x2118: r"""$\wp$""",
    0x211C: r"""$\Re$""",
    0x2120: r"""\textservicemark{}""",
    0x2122: r"""\texttrademark{}""",
    0x2126: r"""$\Omega$""",
    0x212A: r"""K""",
    0x2135: r"""$\aleph$""",
    0x2190: r"""$\leftarrow$""",
    0x2191: r"""$\uparrow$""",
    0x2192: r"""$\rightarrow$""",
    0x2193: r"""$\downarrow$""",
    0x2194: r"""$\leftrightarrow$""",
    0x2195: r"""$\updownarrow$""",
    0x2196: r"""$\nwarrow$""",
    0x2197: r"""$\nearrow$""",
    0x2198: r"""$\searrow$""",
    0x2199: r"""$\swarrow$""",
    0x21A6: r"""$\mapsto$""",
    0x21A9: r"""$\hookleftarrow$""",
    0x21AA: r"""$\hookrightarrow$"""
}

pattern = re.compile(u'([][\\\\#"$%&^_`{}~<>|\u0080-\uFFFD])')

def getPreamble():
    return """\
\\usepackage{textcomp}
\\newcommand{\Special}[1]{{\\fontencoding{T1}\\selectfont\\symbol{#1}}}
"""

def replace(match): return latexForUnicodeChar(match.group(1))

def latexForUnicodeChar(ch):
    code = ord(ch)
    if codeMap.has_key(code): return codeMap[code]
    if code >= 0xC0 and code <= 0xFF: return "\\Special{\"%02X}" % code
    return "[u%04X]" % code

def convert(s):
    s = re.sub(pattern, replace, s)
    return s.encode('ascii')

if __name__ == "__main__":

    names = {
        u'\u0020': 'SPACE',
        u'\u0021': 'EXCLAMATION MARK',
        u'\u0022': 'QUOTATION MARK',
        u'\u0023': 'NUMBER SIGN',
        u'\u0024': 'DOLLAR SIGN',
        u'\u0025': 'PERCENT SIGN',
        u'\u0026': 'AMPERSAND',
        u'\u0027': 'APOSTROPHE',
        u'\u0028': 'LEFT PARENTHESIS',
        u'\u0029': 'RIGHT PARENTHESIS',
        u'\u002A': 'ASTERISK',
        u'\u002B': 'PLUS SIGN',
        u'\u002C': 'COMMA',
        u'\u002D': 'HYPHEN-MINUS',
        u'\u002E': 'FULL STOP',
        u'\u002F': 'SOLIDUS',
        u'\u0030': 'DIGIT ZERO',
        u'\u0031': 'DIGIT ONE',
        u'\u0032': 'DIGIT TWO',
        u'\u0033': 'DIGIT THREE',
        u'\u0034': 'DIGIT FOUR',
        u'\u0035': 'DIGIT FIVE',
        u'\u0036': 'DIGIT SIX',
        u'\u0037': 'DIGIT SEVEN',
        u'\u0038': 'DIGIT EIGHT',
        u'\u0039': 'DIGIT NINE',
        u'\u003A': 'COLON',
        u'\u003B': 'SEMICOLON',
        u'\u003C': 'LESS-THAN SIGN',
        u'\u003D': 'EQUALS SIGN',
        u'\u003E': 'GREATER-THAN SIGN',
        u'\u003F': 'QUESTION MARK',
        u'\u0040': 'COMMERCIAL AT',
        u'\u0041': 'LATIN CAPITAL LETTER A',
        u'\u0042': 'LATIN CAPITAL LETTER B',
        u'\u0043': 'LATIN CAPITAL LETTER C',
        u'\u0044': 'LATIN CAPITAL LETTER D',
        u'\u0045': 'LATIN CAPITAL LETTER E',
        u'\u0046': 'LATIN CAPITAL LETTER F',
        u'\u0047': 'LATIN CAPITAL LETTER G',
        u'\u0048': 'LATIN CAPITAL LETTER H',
        u'\u0049': 'LATIN CAPITAL LETTER I',
        u'\u004A': 'LATIN CAPITAL LETTER J',
        u'\u004B': 'LATIN CAPITAL LETTER K',
        u'\u004C': 'LATIN CAPITAL LETTER L',
        u'\u004D': 'LATIN CAPITAL LETTER M',
        u'\u004E': 'LATIN CAPITAL LETTER N',
        u'\u004F': 'LATIN CAPITAL LETTER O',
        u'\u0050': 'LATIN CAPITAL LETTER P',
        u'\u0051': 'LATIN CAPITAL LETTER Q',
        u'\u0052': 'LATIN CAPITAL LETTER R',
        u'\u0053': 'LATIN CAPITAL LETTER S',
        u'\u0054': 'LATIN CAPITAL LETTER T',
        u'\u0055': 'LATIN CAPITAL LETTER U',
        u'\u0056': 'LATIN CAPITAL LETTER V',
        u'\u0057': 'LATIN CAPITAL LETTER W',
        u'\u0058': 'LATIN CAPITAL LETTER X',
        u'\u0059': 'LATIN CAPITAL LETTER Y',
        u'\u005A': 'LATIN CAPITAL LETTER Z',
        u'\u005B': 'LEFT SQUARE BRACKET',
        u'\u005C': 'REVERSE SOLIDUS',
        u'\u005D': 'RIGHT SQUARE BRACKET',
        u'\u005E': 'CIRCUMFLEX ACCENT',
        u'\u005F': 'LOW LINE',
        u'\u0060': 'GRAVE ACCENT',
        u'\u0061': 'LATIN SMALL LETTER A',
        u'\u0062': 'LATIN SMALL LETTER B',
        u'\u0063': 'LATIN SMALL LETTER C',
        u'\u0064': 'LATIN SMALL LETTER D',
        u'\u0065': 'LATIN SMALL LETTER E',
        u'\u0066': 'LATIN SMALL LETTER F',
        u'\u0067': 'LATIN SMALL LETTER G',
        u'\u0068': 'LATIN SMALL LETTER H',
        u'\u0069': 'LATIN SMALL LETTER I',
        u'\u006A': 'LATIN SMALL LETTER J',
        u'\u006B': 'LATIN SMALL LETTER K',
        u'\u006C': 'LATIN SMALL LETTER L',
        u'\u006D': 'LATIN SMALL LETTER M',
        u'\u006E': 'LATIN SMALL LETTER N',
        u'\u006F': 'LATIN SMALL LETTER O',
        u'\u0070': 'LATIN SMALL LETTER P',
        u'\u0071': 'LATIN SMALL LETTER Q',
        u'\u0072': 'LATIN SMALL LETTER R',
        u'\u0073': 'LATIN SMALL LETTER S',
        u'\u0074': 'LATIN SMALL LETTER T',
        u'\u0075': 'LATIN SMALL LETTER U',
        u'\u0076': 'LATIN SMALL LETTER V',
        u'\u0077': 'LATIN SMALL LETTER W',
        u'\u0078': 'LATIN SMALL LETTER X',
        u'\u0079': 'LATIN SMALL LETTER Y',
        u'\u007A': 'LATIN SMALL LETTER Z',
        u'\u007B': 'LEFT CURLY BRACKET',
        u'\u007C': 'VERTICAL LINE',
        u'\u007D': 'LEFT CURLY BRACKET',
        u'\u007E': 'TILDE',
        u'\u00A0': 'NO-BREAK SPACE',
        u'\u00A1': 'INVERTED EXCLAMATION MARK',
        u'\u00A2': 'CENT SIGN',
        u'\u00A3': 'POUND SIGN',
        u'\u00A4': 'CURRENCY SIGN',
        u'\u00A5': 'YEN SIGN',
        u'\u00A6': 'BROKEN BAR',
        u'\u00A7': 'SECTION SIGN',
        u'\u00A8': 'DIAERESIS',
        u'\u00A9': 'COPYRIGHT SIGN',
        u'\u00AA': 'FEMININE ORDINAL INDICATOR',
        u'\u00AB': 'LEFT-POINTING GUILLEMET',
        u'\u00AC': 'NOT SIGN',
        u'\u00AD': 'SOFT HYPHEN',
        u'\u00AE': 'REGISTERED SIGN',
        u'\u00AF': 'MACRON',
        u'\u00B0': 'DEGREE SIGN',
        u'\u00B1': 'PLUS-MINUS SIGN',
        u'\u00B2': 'SUPERSCRIPT TWO',
        u'\u00B3': 'SUPERSCRIPT THREE',
        u'\u00B4': 'ACUTE ACCENT',
        u'\u00B5': 'MICRO SIGN',
        u'\u00B6': 'PILCROW SIGN',
        u'\u00B7': 'MIDDLE DOT',
        u'\u00B8': 'CEDILLA',
        u'\u00B9': 'SUPERSCRIPT ONE',
        u'\u00BA': 'MASCULINE ORDINAL INDICATOR',
        u'\u00BB': 'RIGHT-POINTING GUILLEMET',
        u'\u00BC': 'VULGAR FRACTION ONE QUARTER',
        u'\u00BD': 'VULGAR FRACTION ONE HALF',
        u'\u00BE': 'VULGAR FRACTION THREE QUARTERS',
        u'\u00BF': 'INVERTED QUESTION MARK',
        u'\u00C0': 'LATIN CAPITAL LETTER A WITH GRAVE',
        u'\u00C1': 'LATIN CAPITAL LETTER A WITH ACUTE',
        u'\u00C2': 'LATIN CAPITAL LETTER A WITH CIRCUMFLEX',
        u'\u00C3': 'LATIN CAPITAL LETTER A WITH TILDE',
        u'\u00C4': 'LATIN CAPITAL LETTER A WITH DIAERESIS',
        u'\u00C5': 'LATIN CAPITAL LETTER A WITH RING ABOVE',
        u'\u00C6': 'LATIN CAPITAL LIGATURE AE',
        u'\u00C7': 'LATIN CAPITAL LETTER C WITH CEDILLA',
        u'\u00C8': 'LATIN CAPITAL LETTER E WITH GRAVE',
        u'\u00C9': 'LATIN CAPITAL LETTER E WITH ACUTE',
        u'\u00CA': 'LATIN CAPITAL LETTER E WITH CIRCUMFLEX',
        u'\u00CB': 'LATIN CAPITAL LETTER E WITH DIAERESIS',
        u'\u00CC': 'LATIN CAPITAL LETTER I WITH GRAVE',
        u'\u00CD': 'LATIN CAPITAL LETTER I WITH ACUTE',
        u'\u00CE': 'LATIN CAPITAL LETTER I WITH CIRCUMFLEX',
        u'\u00CF': 'LATIN CAPITAL LETTER I WITH DIAERESIS',
        u'\u00D0': 'LATIN CAPITAL LETTER ETH',
        u'\u00D1': 'LATIN CAPITAL LETTER N WITH TILDE',
        u'\u00D2': 'LATIN CAPITAL LETTER O WITH GRAVE',
        u'\u00D3': 'LATIN CAPITAL LETTER O WITH ACUTE',
        u'\u00D4': 'LATIN CAPITAL LETTER O WITH CIRCUMFLEX',
        u'\u00D5': 'LATIN CAPITAL LETTER O WITH TILDE',
        u'\u00D6': 'LATIN CAPITAL LETTER O WITH DIAERESIS',
        u'\u00D7': 'MULTIPLICATION SIGN',
        u'\u00D8': 'LATIN CAPITAL LETTER O WITH STROKE',
        u'\u00D9': 'LATIN CAPITAL LETTER U WITH GRAVE',
        u'\u00DA': 'LATIN CAPITAL LETTER U WITH ACUTE',
        u'\u00DB': 'LATIN CAPITAL LETTER U WITH CIRCUMFLEX',
        u'\u00DC': 'LATIN CAPITAL LETTER U WITH DIAERESIS',
        u'\u00DD': 'LATIN CAPITAL LETTER Y WITH ACUTE',
        u'\u00DE': 'LATIN CAPITAL LETTER THORN',
        u'\u00DF': 'LATIN SMALL LETTER SHARP S',
        u'\u00E0': 'LATIN SMALL LETTER A WITH GRAVE',
        u'\u00E1': 'LATIN SMALL LETTER A WITH ACUTE',
        u'\u00E2': 'LATIN SMALL LETTER A WITH CIRCUMFLEX',
        u'\u00E3': 'LATIN SMALL LETTER A WITH TILDE',
        u'\u00E4': 'LATIN SMALL LETTER A WITH DIAERESIS',
        u'\u00E5': 'LATIN SMALL LETTER A WITH RING ABOVE',
        u'\u00E6': 'LATIN SMALL LIGATURE AE',
        u'\u00E7': 'LATIN SMALL LETTER C WITH CEDILLA',
        u'\u00E8': 'LATIN SMALL LETTER E WITH GRAVE',
        u'\u00E9': 'LATIN SMALL LETTER E WITH ACUTE',
        u'\u00EA': 'LATIN SMALL LETTER E WITH CIRCUMFLEX',
        u'\u00EB': 'LATIN SMALL LETTER E WITH DIAERESIS',
        u'\u00EC': 'LATIN SMALL LETTER I WITH GRAVE',
        u'\u00ED': 'LATIN SMALL LETTER I WITH ACUTE',
        u'\u00EE': 'LATIN SMALL LETTER I WITH CIRCUMFLEX',
        u'\u00EF': 'LATIN SMALL LETTER I WITH DIAERESIS',
        u'\u00F0': 'LATIN SMALL LETTER ETH',
        u'\u00F1': 'LATIN SMALL LETTER N WITH TILDE',
        u'\u00F2': 'LATIN SMALL LETTER O WITH GRAVE',
        u'\u00F3': 'LATIN SMALL LETTER O WITH ACUTE',
        u'\u00F4': 'LATIN SMALL LETTER O WITH CIRCUMFLEX',
        u'\u00F5': 'LATIN SMALL LETTER O WITH TILDE',
        u'\u00F6': 'LATIN SMALL LETTER O WITH DIAERESIS',
        u'\u00F7': 'DIVISION SIGN',
        u'\u00F8': 'LATIN SMALL LETTER O WITH STROKE',
        u'\u00F9': 'LATIN SMALL LETTER U WITH GRAVE',
        u'\u00FA': 'LATIN SMALL LETTER U WITH ACUTE',
        u'\u00FB': 'LATIN SMALL LETTER U WITH CIRCUMFLEX',
        u'\u00FC': 'LATIN SMALL LETTER U WITH DIAERESIS',
        u'\u00FD': 'LATIN SMALL LETTER Y WITH ACUTE',
        u'\u00FE': 'LATIN SMALL LETTER THORN',
        u'\u00FF': 'LATIN SMALL LETTER Y WITH DIAERESIS',
        u'\u0100': 'LATIN CAPITAL LETTER A WITH MACRON',
        u'\u0101': 'LATIN SMALL LETTER A WITH MACRON',
        u'\u0102': 'LATIN CAPITAL LETTER A WITH BREVE',
        u'\u0103': 'LATIN SMALL LETTER A WITH BREVE',
        u'\u0104': 'LATIN CAPITAL LETTER A WITH OGONEK',
        u'\u0105': 'LATIN SMALL LETTER A WITH OGONEK',
        u'\u0106': 'LATIN CAPITAL LETTER C WITH ACUTE',
        u'\u0107': 'LATIN SMALL LETTER C WITH ACUTE',
        u'\u0108': 'LATIN CAPITAL LETTER C WITH CIRCUMFLEX',
        u'\u0109': 'LATIN SMALL LETTER C WITH CIRCUMFLEX',
        u'\u010A': 'LATIN CAPITAL LETTER C WITH DOT ABOVE',
        u'\u010B': 'LATIN SMALL LETTER C WITH DOT ABOVE',
        u'\u010C': 'LATIN CAPITAL LETTER C WITH CARON',
        u'\u010D': 'LATIN SMALL LETTER C WITH CARON',
        u'\u010E': 'LATIN CAPITAL LETTER D WITH CARON',
        u'\u010F': 'LATIN SMALL LETTER D WITH CARON',
        u'\u0110': 'LATIN CAPITAL LETTER D WITH STROKE',
        u'\u0111': 'LATIN SMALL LETTER D WITH STROKE',
        u'\u0112': 'LATIN CAPITAL LETTER E WITH MACRON',
        u'\u0113': 'LATIN SMALL LETTER E WITH MACRON',
        u'\u0114': 'LATIN CAPITAL LETTER E WITH BREVE',
        u'\u0115': 'LATIN SMALL LETTER E WITH BREVE',
        u'\u0116': 'LATIN CAPITAL LETTER E WITH DOT ABOVE',
        u'\u0117': 'LATIN SMALL LETTER E WITH DOT ABOVE',
        u'\u0118': 'LATIN CAPITAL LETTER E WITH OGONEK',
        u'\u0119': 'LATIN SMALL LETTER E WITH OGONEK',
        u'\u011A': 'LATIN CAPITAL LETTER E WITH CARON',
        u'\u011B': 'LATIN SMALL LETTER E WITH CARON',
        u'\u011C': 'LATIN CAPITAL LETTER G WITH CIRCUMFLEX',
        u'\u011D': 'LATIN SMALL LETTER G WITH CIRCUMFLEX',
        u'\u011E': 'LATIN CAPITAL LETTER G WITH BREVE',
        u'\u011F': 'LATIN SMALL LETTER G WITH BREVE',
        u'\u0120': 'LATIN CAPITAL LETTER G WITH DOT ABOVE',
        u'\u0121': 'LATIN SMALL LETTER G WITH DOT ABOVE',
        u'\u0122': 'LATIN CAPITAL LETTER G WITH CEDILLA',
        u'\u0123': 'LATIN SMALL LETTER G WITH CEDILLA',
        u'\u0124': 'LATIN CAPITAL LETTER H WITH CIRCUMFLEX',
        u'\u0125': 'LATIN SMALL LETTER H WITH CIRCUMFLEX',
        u'\u0128': 'LATIN CAPITAL LETTER I WITH TILDE',
        u'\u0129': 'LATIN SMALL LETTER I WITH TILDE',
        u'\u012A': 'LATIN CAPITAL LETTER I WITH MACRON',
        u'\u012B': 'LATIN SMALL LETTER I WITH MACRON',
        u'\u012C': 'LATIN CAPITAL LETTER I WITH BREVE',
        u'\u012D': 'LATIN SMALL LETTER I WITH BREVE',
        u'\u0130': 'LATIN CAPITAL LETTER I WITH DOT ABOVE',
        u'\u0131': 'LATIN SMALL LETTER DOTLESS I',
        u'\u0132': 'LATIN CAPITAL LIGATURE IJ',
        u'\u0133': 'LATIN SMALL LIGATURE IJ',
        u'\u0134': 'LATIN CAPITAL LETTER J WITH CIRCUMFLEX',
        u'\u0135': 'LATIN SMALL LETTER J WITH CIRCUMFLEX',
        u'\u0136': 'LATIN CAPITAL LETTER K WITH CEDILLA',
        u'\u0137': 'LATIN SMALL LETTER K WITH CEDILLA',
        u'\u0139': 'LATIN CAPITAL LETTER L WITH ACUTE',
        u'\u013A': 'LATIN SMALL LETTER L WITH ACUTE',
        u'\u013B': 'LATIN CAPITAL LETTER L WITH CEDILLA',
        u'\u013C': 'LATIN SMALL LETTER L WITH CEDILLA',
        u'\u013D': 'LATIN CAPITAL LETTER L WITH CARON',
        u'\u013E': 'LATIN SMALL LETTER L WITH CARON',
        u'\u013F': 'LATIN CAPITAL LETTER L WITH MIDDLE DOT',
        u'\u0140': 'LATIN SMALL LETTER L WITH MIDDLE DOT',
        u'\u0141': 'LATIN CAPITAL LETTER L WITH STROKE',
        u'\u0142': 'LATIN SMALL LETTER L WITH STROKE',
        u'\u0143': 'LATIN CAPITAL LETTER N WITH ACUTE',
        u'\u0144': 'LATIN SMALL LETTER N WITH ACUTE',
        u'\u0145': 'LATIN CAPITAL LETTER N WITH CEDILLA',
        u'\u0146': 'LATIN SMALL LETTER N WITH CEDILLA',
        u'\u0147': 'LATIN CAPITAL LETTER N WITH CARON',
        u'\u0148': 'LATIN SMALL LETTER N WITH CARON',
        u'\u0149': 'LATIN SMALL LETTER N PRECEDED BY APOSTROPHE',
        u'\u014A': 'LATIN CAPITAL LETTER ENG',
        u'\u014B': 'LATIN SMALL LETTER ENG',
        u'\u014C': 'LATIN CAPITAL LETTER O WITH MACRON',
        u'\u014D': 'LATIN SMALL LETTER O WITH MACRON',
        u'\u014E': 'LATIN CAPITAL LETTER O WITH BREVE',
        u'\u014F': 'LATIN SMALL LETTER O WITH BREVE',
        u'\u0150': 'LATIN CAPITAL LETTER O WITH DOUBLE ACUTE',
        u'\u0151': 'LATIN SMALL LETTER O WITH DOUBLE ACUTE',
        u'\u0152': 'LATIN CAPITAL LIGATURE OE',
        u'\u0153': 'LATIN SMALL LIGATURE OE',
        u'\u0154': 'LATIN CAPITAL LETTER R WITH ACUTE',
        u'\u0155': 'LATIN SMALL LETTER R WITH ACUTE',
        u'\u0156': 'LATIN CAPITAL LETTER R WITH CEDILLA',
        u'\u0157': 'LATIN SMALL LETTER R WITH CEDILLA',
        u'\u0158': 'LATIN CAPITAL LETTER R WITH CARON',
        u'\u0159': 'LATIN SMALL LETTER R WITH CARON',
        u'\u015A': 'LATIN CAPITAL LETTER S WITH ACUTE',
        u'\u015B': 'LATIN SMALL LETTER S WITH ACUTE',
        u'\u015C': 'LATIN CAPITAL LETTER S WITH CIRCUMFLEX',
        u'\u015D': 'LATIN SMALL LETTER S WITH CIRCUMFLEX',
        u'\u015E': 'LATIN CAPITAL LETTER S WITH CEDILLA',
        u'\u015F': 'LATIN SMALL LETTER S WITH CEDILLA',
        u'\u0160': 'LATIN CAPITAL LETTER S WITH CARON',
        u'\u0161': 'LATIN SMALL LETTER S WITH CARON',
        u'\u0162': 'LATIN CAPITAL LETTER T WITH CEDILLA',
        u'\u0163': 'LATIN SMALL LETTER T WITH CEDILLA',
        u'\u0164': 'LATIN CAPITAL LETTER T WITH CARON',
        u'\u0165': 'LATIN SMALL LETTER T WITH CARON',
        u'\u0168': 'LATIN CAPITAL LETTER U WITH TILDE',
        u'\u0169': 'LATIN SMALL LETTER U WITH TILDE',
        u'\u016A': 'LATIN CAPITAL LETTER U WITH MACRON',
        u'\u016B': 'LATIN SMALL LETTER U WITH MACRON',
        u'\u016C': 'LATIN CAPITAL LETTER U WITH BREVE',
        u'\u016D': 'LATIN SMALL LETTER U WITH BREVE',
        u'\u016E': 'LATIN CAPITAL LETTER U WITH RING ABOVE',
        u'\u016F': 'LATIN SMALL LETTER U WITH RING ABOVE',
        u'\u0170': 'LATIN CAPITAL LETTER U WITH DOUBLE ACUTE',
        u'\u0171': 'LATIN SMALL LETTER U WITH DOUBLE ACUTE',
        u'\u0174': 'LATIN CAPITAL LETTER W WITH CIRCUMFLEX',
        u'\u0175': 'LATIN SMALL LETTER W WITH CIRCUMFLEX',
        u'\u0176': 'LATIN CAPITAL LETTER Y WITH CIRCUMFLEX',
        u'\u0177': 'LATIN SMALL LETTER Y WITH CIRCUMFLEX',
        u'\u0178': 'LATIN CAPITAL LETTER Y WITH DIAERESIS',
        u'\u0179': 'LATIN CAPITAL LETTER Z WITH ACUTE',
        u'\u017A': 'LATIN SMALL LETTER Z WITH ACUTE',
        u'\u017B': 'LATIN CAPITAL LETTER Z WITH DOT ABOVE',
        u'\u017C': 'LATIN SMALL LETTER Z WITH DOT ABOVE',
        u'\u017D': 'LATIN CAPITAL LETTER Z WITH CARON',
        u'\u017E': 'LATIN SMALL LETTER Z WITH CARON',
        u'\u01CD': 'LATIN CAPITAL LETTER A WITH CARON',
        u'\u01CE': 'LATIN SMALL LETTER A WITH CARON',
        u'\u01CF': 'LATIN CAPITAL LETTER I WITH CARON',
        u'\u01D0': 'LATIN SMALL LETTER I WITH CARON',
        u'\u01D1': 'LATIN CAPITAL LETTER O WITH CARON',
        u'\u01D2': 'LATIN SMALL LETTER O WITH CARON',
        u'\u01D3': 'LATIN CAPITAL LETTER U WITH CARON',
        u'\u01D4': 'LATIN SMALL LETTER U WITH CARON',
        u'\u01E2': 'LATIN CAPITAL LETTER AE WITH MACRON',
        u'\u01E3': 'LATIN SMALL LETTER AE WITH MACRON',
        u'\u01E6': 'LATIN CAPITAL LETTER G WITH CARON',
        u'\u01E7': 'LATIN SMALL LETTER G WITH CARON',
        u'\u01E8': 'LATIN CAPITAL LETTER K WITH CARON',
        u'\u01E9': 'LATIN SMALL LETTER K WITH CARON',
        u'\u01F4': 'LATIN CAPITAL LETTER G WITH ACUTE',
        u'\u01F5': 'LATIN SMALL LETTER G WITH ACUTE',
        u'\u01FC': 'LATIN CAPITAL LETTER AE WITH ACUTE',
        u'\u01FD': 'LATIN SMALL LETTER AE WITH ACUTE',
        u'\u02D8': 'BREVE',
        u'\u02D9': 'DOT ABOVE',
        u'\u0300': 'COMBINING GRAVE ACCENT',
        u'\u0301': 'COMBINING ACUTE ACCENT',
        u'\u0302': 'COMBINING CIRCUMFLEX ACCENT',
        u'\u0303': 'COMBINING TILDE',
        u'\u0304': 'COMBINING MACRON',
        u'\u0306': 'COMBINING BREVE',
        u'\u0307': 'COMBINING DOT ABOVE',
        u'\u0308': 'COMBINING DIAERESIS',
        u'\u030B': 'COMBINING DOUBLE ACUTE ACCENT',
        u'\u030C': 'COMBINING CARON',
        u'\u0327': 'COMBINING CEDILLA',
        u'\u0391': 'GREEK CAPITAL LETTER ALPHA',
        u'\u0392': 'GREEK CAPITAL LETTER BETA',
        u'\u0393': 'GREEK CAPITAL LETTER GAMMA',
        u'\u0394': 'GREEK CAPITAL LETTER DELTA',
        u'\u0395': 'GREEK CAPITAL LETTER EPSILON',
        u'\u0396': 'GREEK CAPITAL LETTER ZETA',
        u'\u0397': 'GREEK CAPITAL LETTER ETA',
        u'\u0398': 'GREEK CAPITAL LETTER THETA',
        u'\u0399': 'GREEK CAPITAL LETTER IOTA',
        u'\u039A': 'GREEK CAPITAL LETTER KAPPA',
        u'\u039B': 'GREEK CAPITAL LETTER LAMDA',
        u'\u039C': 'GREEK CAPITAL LETTER MU',
        u'\u039D': 'GREEK CAPITAL LETTER NU',
        u'\u039E': 'GREEK CAPITAL LETTER XI',
        u'\u039F': 'GREEK CAPITAL LETTER OMICRON',
        u'\u03A0': 'GREEK CAPITAL LETTER PI',
        u'\u03A1': 'GREEK CAPITAL LETTER RHO',
        u'\u03A3': 'GREEK CAPITAL LETTER SIGMA',
        u'\u03A4': 'GREEK CAPITAL LETTER TAU',
        u'\u03A5': 'GREEK CAPITAL LETTER UPSILON',
        u'\u03A6': 'GREEK CAPITAL LETTER PHI',
        u'\u03A7': 'GREEK CAPITAL LETTER CHI',
        u'\u03A8': 'GREEK CAPITAL LETTER PSI',
        u'\u03A9': 'GREEK CAPITAL LETTER OMEGA',
        u'\u03B1': 'GREEK SMALL LETTER ALPHA',
        u'\u03B2': 'GREEK SMALL LETTER BETA',
        u'\u03B3': 'GREEK SMALL LETTER GAMMA',
        u'\u03B4': 'GREEK SMALL LETTER DELTA',
        u'\u03B5': 'GREEK SMALL LETTER EPSILON',
        u'\u03B6': 'GREEK SMALL LETTER ZETA',
        u'\u03B7': 'GREEK SMALL LETTER ETA',
        u'\u03B8': 'GREEK SMALL LETTER THETA',
        u'\u03B9': 'GREEK SMALL LETTER IOTA',
        u'\u03BA': 'GREEK SMALL LETTER KAPPA',
        u'\u03BB': 'GREEK SMALL LETTER LAMDA',
        u'\u03BC': 'GREEK SMALL LETTER MU',
        u'\u03BD': 'GREEK SMALL LETTER NU',
        u'\u03BE': 'GREEK SMALL LETTER XI',
        u'\u03BF': 'GREEK SMALL LETTER OMICRON',
        u'\u03D1': 'GREEK THETA SYMBOL',
        u'\u03D5': 'GREEK PHI SYMBOL',
        u'\u03D6': 'GREEK PI SYMBOL',
        u'\u03F1': 'GREEK RHO SYMBOL',
        u'\u2009': 'THIN SPACE',
        u'\u2010': 'HYPHEN',
        u'\u2011': 'NON-BREAKING HYPHEN',
        u'\u2013': 'EN DASH',
        u'\u2014': 'EM DASH',
        u'\u2016': 'DOUBLE VERTICAL LINE',
        u'\u2020': 'DAGGER',
        u'\u2021': 'DOUBLE DAGGER',
        u'\u2022': 'BULLET',
        u'\u2026': 'HORIZONTAL ELLIPSIS',
        u'\u2032': 'PRIME',
        u'\u2038': 'CARET',
        u'\u2070': 'SUPERSCRIPT ZERO',
        u'\u2074': 'SUPERSCRIPT FOUR',
        u'\u2075': 'SUPERSCRIPT FIVE',
        u'\u2076': 'SUPERSCRIPT SIX',
        u'\u2077': 'SUPERSCRIPT SEVEN',
        u'\u2078': 'SUPERSCRIPT EIGHT',
        u'\u2079': 'SUPERSCRIPT NINE',
        u'\u207A': 'SUPERSCRIPT PLUS SIGN',
        u'\u207B': 'SUPERSCRIPT MINUS',
        u'\u207C': 'SUPERSCRIPT EQUALS SIGN',
        u'\u207D': 'SUPERSCRIPT LEFT PARENTHESIS',
        u'\u207E': 'SUPERSCRIPT RIGHT PARENTHESIS',
        u'\u207F': 'SUPERSCRIPT LATIN SMALL LETTER N',
        u'\u2080': 'SUBSCRIPT ZERO',
        u'\u2081': 'SUBSCRIPT ONE',
        u'\u2082': 'SUBSCRIPT TWO',
        u'\u2083': 'SUBSCRIPT THREE',
        u'\u2084': 'SUBSCRIPT FOUR',
        u'\u2085': 'SUBSCRIPT FIVE',
        u'\u2086': 'SUBSCRIPT SIX',
        u'\u2087': 'SUBSCRIPT SEVEN',
        u'\u2088': 'SUBSCRIPT EIGHT',
        u'\u2089': 'SUBSCRIPT NINE',
        u'\u208A': 'SUBSCRIPT PLUS SIGN',
        u'\u208B': 'SUBSCRIPT MINUS',
        u'\u208C': 'SUBSCRIPT EQUALS SIGN',
        u'\u208D': 'SUBSCRIPT LEFT PARENTHESIS',
        u'\u208E': 'SUBSCRIPT RIGHT PARENTHESIS',
        u'\u2107': 'EULER CONSTANT',
        u'\u210E': 'PLANCK CONSTANT',
        u'\u210F': 'PLANCK CONSTANT OVER TWO PI',
        u'\u2111': 'BLACK-LETTER CAPITAL I',
        u'\u2113': 'SCRIPT SMALL L',
        u'\u2118': 'SCRIPT CAPITAL P',
        u'\u211C': 'BLACK-LETTER CAPITAL R',
        u'\u2120': 'SERVICE MARK',
        u'\u2122': 'TRADE MARK SIGN',
        u'\u2126': 'OHM SIGN',
        u'\u212A': 'KELVIN SIGN',
        u'\u2135': 'ALEF SYMBOL',
        u'\u2190': 'LEFTWARDS ARROW',
        u'\u2191': 'UPWARDS ARROW',
        u'\u2192': 'RIGHTWARDS ARROW',
        u'\u2193': 'DOWNWARDS ARROW',
        u'\u2194': 'LEFT RIGHT ARROW',
        u'\u2195': 'UP DOWN ARROW',
        u'\u2196': 'NORTH WEST ARROW',
        u'\u2197': 'NORTH EAST ARROW',
        u'\u2198': 'SOUTH EAST ARROW',
        u'\u2199': 'SOUTH WEST ARROW',
        u'\u21A6': 'RIGHTWARDS ARROW FROM BAR',
        u'\u21A9': 'LEFTWARDS ARROW WITH HOOK',
        u'\u21AA': 'RIGHTWARDS ARROW WITH HOOK'
    }
    chars = names.keys()
    chars.sort()
    print """\
\\documentclass{article}
\\usepackage{textcomp}
\\newcommand{\Special}[1]{{\\fontencoding{T1}\\selectfont\\symbol{#1}}}
\\begin{document}

Here are the Unicode characters we can handle so far: \\\\ \\\\ """
    for char in chars:
        code = ord(char)
        line = u"[%04X] A%sZ a%sz [%s]" % (code, char, char, names[char])
        print convert(line) + " \\\\"
    print "\\end{document}"
